# Generated by Django 5.1.15 on 2026-09-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('ip', 'IP Address'), ('token', 'JWT Token JTI')], default='ip', max_length=10)),
                ('value', models.CharField(db_index=True, max_length=255, unique=True)),
                ('reason', models.TextField(blank=True, default='Suspicious or abusive activity')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.CharField(db_index=True, max_length=64)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(db_index=True, max_length=255)),
                ('status_code', models.IntegerField(db_index=True)),
                ('response_time_ms', models.FloatField(help_text='Execution latency in milliseconds')),
                ('db_query_count', models.IntegerField(default=0, help_text='Number of SQL queries executed')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('cache_hit', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='core_reques_created_e60492_idx'), models.Index(fields=['trace_id'], name='core_reques_trace_i_20bd90_idx'), models.Index(fields=['status_code'], name='core_reques_status__03d0e3_idx')],
            },
        ),
    ]
